[package]
name = "ggez_tests"
version = "0.1.0"
authors = ["Sevajol Bastien <contact@bux.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
